### PR TITLE
Split definition into different modules

### PR DESCRIPTION
**Pull request by david0u0**
issue #60

Add a new optional argument `with_idents` for `graphql_schema_from_file!`. The usage is as fallowing:
```rust
graphql_schema_from_file!(
    "tests/schemas/complex_schema.graphql",
    with_idents: [Character, Droid, Human]
);
pub struct Human { }
impl HumanFields for Human {
    /* implementation */
}
pub struct Droid { }
impl DroidFields for Droid {
    /* implementation */
}
// Character is a graphql interface, hence no need to implement it.
```

tests suits:
1. tests/compile_pass/with_idents.rs
2. tests/compile_fail/wrong_with_ident_value.rs
3. tests/split_mod_test.rs

p,s. Some test suits have already failed since I forked them, don't know if I should fix them.

### CODE REVIEW

**Comment by david0u0** [comment]
Some test suits have already been wrong since I forked them. I don't know if I should modify them.

**Comment by davidpdrsn** [comment]
Sorry for taking so long to review this, but I think I'm going to close this PR and the related issue. I think it makes more sense to look into when Juniper has a good solution for it. This is also not a feature I can see myself using so while I'm the sole maintainer of crate I wouldn't feel good about taking on feature.

Hopefully you understand 😊 You're of course welcome to experiment with this in a fork and submit a new PR once you have something you're happy with.

**Comment by qmx** [comment]
@davidpdrsn I totally understand your maintenance concern.

What could we do to make you more comfortable with a change like this? I'm trying to think on a reasonable middle ground where we can get the features this crate offers today without putting a big burden on you.

Any Ideas on how to make the code generation more modular? In my case I have separate definitions for the various types but would just implement the `Query` in juniper directly (and consequently `QueryTrail` too.

I'm happy to assist with a PR, although I want to make sure this is something you would be ok with vs me maintaining a private fork with a feature that will never see the light of the day :)

**Comment by davidpdrsn** [comment]
Sorry for taking a while to answer.

I can’t really think of any good approaches at the moment tbh. I guess someone would have to experiment in a fork or a new crate. Keep in mind that this crate doesn’t do anything you cannot do by hand with straight juniper. So it is a about finding a structure that works well and then seeing how that can be incorporated.

**Pull request closed without merging**
