### PR TITLE
Derive Clone for inputs

### LINKED ISSUE #110: Input clone ?
How do you manage to clone a GraphQL input ?
For example I have one input and i need to create two objects from it (I have implemented from but it move the object). 
The Clone is not implemented on the input object. Is there any easy way to do that ? (Using the directive ?)

### PR DESCRIPTION
**Pull request by Farkal**
Resolve #110 

I also added badges because I find it easier to see than a link pointing to the doc inside the readme but i can remove them if you want ;)

### CODE REVIEW

**Comment by davidpdrsn** [comment]
Looks good 👍

Will you update the changelog as well?

**Comment by Farkal** [comment]
Done ;)
I let you submit a new release ?

**Comment by davidpdrsn** [comment]
Thanks!

**Comment by davidpdrsn** [comment]
This was just shipped as part of 0.5.2

**Pull request merged**
