### PR TITLE
Support directive definitions in schema

### PR DESCRIPTION
**Pull request by davidpdrsn**
Fixes https://github.com/davidpdrsn/juniper-from-schema/issues/103

### CODE REVIEW

**Comment by davidpdrsn** [comment]
@onelson This should fix your issues. Are you able to try and build with this PR?

Changing your Cargo.toml to

```toml
juniper-from-schema = { git = "https://github.com/davidpdrsn/juniper-from-schema.git", branch = "support-directive-definitions" }
```

and adding this to your GraphQL schema

```graphql
directive @juniper(
    ownership: String = "borrowed",
    infallible: Boolean = false,
    with_time_zone: Boolean = true
) on FIELD_DEFINITION
```

should do the trick.

Let me know if it is working for you.

**Comment by onelson** [comment]
Sorry for the delay! I'll check shortly.

**Comment by onelson** [comment]
Everything looks great from my end. I was able to update my project to use a single schema file, with the directive definition in it.

https://github.com/onelson/e2e-rs/commit/7ca1518689c430b4f100992df53593105d5ec891

Client-side and server-side codegen tools were happy to consume the file. My IDE was also happy to provide good inspections based on this!

Thanks so much for considering this feature request. Having to include the directive definition on my side feels a little clunky, but this is far better than having to sed the schema so other tools can consume it.

**Comment by davidpdrsn** [comment]
Perfect 👌 

I'll publish a release this week.

**Comment by davidpdrsn** [comment]
This was just shipped as part of 0.5.2

**Pull request merged**
